//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbBank
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<bool> NotInUse { get; set; }
    public int Bid { get; set; }
}

public partial class tbBranch
{
    public int Id { get; set; }
    public Nullable<int> BankID { get; set; }
    public string Name { get; set; }
}

public partial class tbCommon
{
    public int Id { get; set; }
    public Nullable<double> Nds { get; set; }
    public Nullable<int> LastBKMId { get; set; }
}

public partial class tbCompany
{
    public int Id { get; set; }
    public string EName { get; set; }
    public string Name { get; set; }
    public string SubTitle { get; set; }
    public string ESubTitle { get; set; }
    public string Identificator { get; set; }
    public string Street { get; set; }
    public string City { get; set; }
    public string Country { get; set; }
    public string EAddress { get; set; }
    public string Index { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }
    public string Mobile { get; set; }
    public string InvName { get; set; }
    public string InvMail { get; set; }
    public string PayName { get; set; }
    public string BankName { get; set; }
    public string Branch { get; set; }
    public string Account { get; set; }
    public string SWIFT { get; set; }
    public string IBAN { get; set; }
    public string EPayName { get; set; }
    public string EBankName { get; set; }
    public string EBankAddress { get; set; }
    public Nullable<bool> IsArchive { get; set; }
    public string Logo { get; set; }
    public Nullable<bool> IsLocked { get; set; }
    public string CardExp { get; set; }
    public string CardNds { get; set; }
    public string KupatCash { get; set; }
    public string KupatChecks { get; set; }
    public string CodeA1 { get; set; }
    public string CodeA2 { get; set; }
}

public partial class tbCompanyCustomer
{
    public int Id { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public Nullable<int> CustomerID { get; set; }
}

public partial class tbCustomer
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Identificator { get; set; }
    public string AStreet { get; set; }
    public string ACity { get; set; }
    public string AIndex { get; set; }
    public string ACountry { get; set; }
    public string CName { get; set; }
    public string CEmail { get; set; }
    public string CPhone { get; set; }
    public string CMobile { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public string BankName { get; set; }
    public string Branch { get; set; }
    public string Account { get; set; }
    public string PayName { get; set; }
    public Nullable<bool> IsArchive { get; set; }
    public string CardID { get; set; }
    public string Comments { get; set; }
}

public partial class tbDocumentNumber
{
    public int Id { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public Nullable<int> DocID { get; set; }
    public Nullable<int> Start { get; set; }
    public Nullable<int> Last { get; set; }
    public Nullable<bool> IsActive { get; set; }
}

public partial class tbDocumentPayment
{
    public int Id { get; set; }
    public Nullable<int> DocID { get; set; }
    public Nullable<int> TypeID { get; set; }
    public string Type { get; set; }
    public Nullable<int> BankCode { get; set; }
    public Nullable<int> BranchCode { get; set; }
    public string Account { get; set; }
    public string Check { get; set; }
    public Nullable<double> Total { get; set; }
    public string Comments { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
}

public partial class tbDocumentProduct
{
    public int Id { get; set; }
    public Nullable<int> DocumentID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public string Name { get; set; }
    public double Price { get; set; }
    public double Amount { get; set; }
    public string Info { get; set; }
}

public partial class tbDocumentType
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string IPCode { get; set; }
    public Nullable<bool> IsArchive { get; set; }
}

public partial class tbProduct
{
    public int Id { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public string Makat { get; set; }
    public string Name { get; set; }
    public Nullable<decimal> Price { get; set; }
    public string Description { get; set; }
    public Nullable<bool> IsArchive { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<bool> IsNew { get; set; }
    public string Info { get; set; }
}

public partial class tbUser
{
    public int Id { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
    public string Password { get; set; }
    public System.DateTime RegDate { get; set; }
    public string Email { get; set; }
    public string Identificator { get; set; }
    public Nullable<bool> IsAdmin { get; set; }
    public Nullable<bool> IsArchive { get; set; }
}

public partial class tbUserCompany
{
    public int Id { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public Nullable<bool> IsArchive { get; set; }
}

public partial class tbUserCustomer
{
    public int Id { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<int> CustomerID { get; set; }
    public Nullable<bool> IsArchive { get; set; }
}

public partial class tbUserDocument
{
    public int Id { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<int> DocumentType { get; set; }
    public Nullable<int> DocumentNumber { get; set; }
    public System.DateTime Date { get; set; }
    public Nullable<System.DateTime> DueDate { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public string CompanyIdentificator { get; set; }
    public string CompanyName { get; set; }
    public string CompanyAddress { get; set; }
    public string CompanyPhone { get; set; }
    public string CompanyMail { get; set; }
    public Nullable<int> CustomerID { get; set; }
    public string CustomerIdentificator { get; set; }
    public string CustomerName { get; set; }
    public string CustomerAddress { get; set; }
    public string CustomerPhone { get; set; }
    public string CustomerMail { get; set; }
    public Nullable<decimal> Nds { get; set; }
    public Nullable<bool> NdsInc { get; set; }
    public Nullable<decimal> Discount { get; set; }
    public Nullable<bool> DiscPer { get; set; }
    public Nullable<decimal> Total { get; set; }
    public Nullable<decimal> NdsV { get; set; }
    public Nullable<decimal> DiscV { get; set; }
    public string Comments { get; set; }
    public Nullable<decimal> PaidTotal { get; set; }
    public Nullable<decimal> MasBaMakor { get; set; }
    public Nullable<bool> IsDraft { get; set; }
    public Nullable<bool> IsArchive { get; set; }
    public Nullable<int> CancelID { get; set; }
    public string CancelMsg { get; set; }
    public Nullable<bool> IsCanceled { get; set; }
    public Nullable<System.DateTime> CreationDate { get; set; }
    public string CustomerACountry { get; set; }
    public string CustomerACity { get; set; }
    public string CustomerAStreet { get; set; }
    public string CustomerAIndex { get; set; }
    public Nullable<int> DocStatus { get; set; }
    public Nullable<bool> isClosed { get; set; }
    public Nullable<int> LinkedDocID { get; set; }
    public Nullable<int> ParentDocID { get; set; }
}

public partial class vDocCompAndType
{
    public int Id { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public string IPCode { get; set; }
}

public partial class spGetUserData_Result
{
    public int Id { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
    public string Password { get; set; }
    public System.DateTime RegDate { get; set; }
    public string Email { get; set; }
    public string Identificator { get; set; }
    public Nullable<bool> IsAdmin { get; set; }
    public Nullable<bool> IsArchive { get; set; }
}
